AWSTemplateFormatVersion: 2010-09-09
Parameters:
  NetworkStackName:
    Description: Name of an  active CloudFormation stack that contains the networking resources, such as the subnet and security group, that will be used in this stack.
    Type: String
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
    Default: networkstack
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: 'AWS::EC2::KeyPair::KeyName'
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Mappings:
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: '{{resolve:ssm:us-east-1-hvm64:1}}'
    us-east-2:
      HVM64: '{{resolve:ssm:us-east-2-hvm64:1}}'
    us-west-1:
      HVM64: '{{resolve:ssm:us-west-1-hvm64:1}}'
    us-west-2:
      HVM64: '{{resolve:ssm:us-west-2-hvm64:1}}'
Resources:
  EC2InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation
      VpcId:
        Fn::ImportValue: !Sub '${NetworkStackName}-VPCID'
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap 
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref EC2InstanceSecurityGroup
      KeyName: !Ref KeyName
      SubnetId:
        Fn::ImportValue: !Sub '${NetworkStackName}-PUBLICSUBNET01'