---
AWSTemplateFormatVersion: 2010-09-09

Description:
  This template creates an EC2 instance based on the region and selection of an AMI ID. It will also create a Security Group.

Parameters:
  Subnet:
    Type: String
    Default: subnet-00c406737faae6fb5
    Description: Choose a subnet from your VPC.
  SecurityGroup:
    Type: String
    Default: sg-0c8d7680e19f854f7
    Description: Choose a security group from your VPC.
  KeyName:
    Type: 'AWS::EC2::KeyPair::KeyName'
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3a.micro
      - t3.micro
    Description: Enter the desired instance type.
    ConstraintDescription: Must be a valid EC2 instance type.
  SSHLocation:
    Type: String
    Default: 0.0.0.0/0
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.

Mappings:
  AWSRegionAMI:
    us-east-1:
      HVM64: ami-0080e4c5bc078760e
    us-east-2:
      HVM64: ami-0cd3dfa4e37921605
    us-west-1:
      HVM64: ami-0ec6517f6edbf8044
    us-west-2:
      HVM64: ami-01e24be29428c15b2

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref Subnet
      SecurityGroupIds:
        - !Ref SecurityGroup
      KeyName: !Ref KeyName
      ImageId: !FindInMap
        - AWSRegionAMI
        - !Ref 'AWS::Region'
        - HVM64

Outputs:
  InstanceID:
    Description: The instance ID.
    Value: !Ref EC2Instance
  AvailabilityZone:
    Description: The AZ of the instance.
    Value: !GetAtt EC2Instance.AvailabilityZone
  PublicDNS:
    Description: The Public DNS Name of the instance.
    Value: !GetAtt EC2Instance.PublicDnsName
  PublicIP:
    Description: The Public IP Address of the instance.
    Value: !GetAtt EC2Instance.PublicIp
